Swik 1280 username case insensitive
slidewiki/user-service pull request #22
Opened 2017-05-31 13:10 UTC by TBoonX

I made that usernames have to be alphanumeric and could also contain -._~
I added checking and parsing. I made sure that the upper cases of usernames last.
I also improved the reading/parsing/usage of the email parameter. (**urgent**)
There is now a migration script which I described to ben and which will also be added to the migration repo.

2017-06-01 08:13 UTC, rmeissn commented
Can you please resolve the conflicts of this PR? I will review it today.

2017-06-06 11:23 UTC, rmeissn requested changes

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +          email: new RegExp(req.payload.email, 'i')
use .tolowercase() instead and make sure every email in the DB is lowercase (by migrating them once and saving new emails as lowercase)

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +            username:    util.parseAPIParameter(req.payload.username).replace(/\s/g,''),
Redundant to remove whitspaces because they are already handled at the route itself

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +    let identifier = decodeURI(req.params.identifier).replace(/\s/g,'');
Handle all chars correctly

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +          username: new RegExp(username, 'i')
Partly same as first comment, make regex exact match

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +          email: new RegExp(email, 'i')
Same as first comment

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +              email: new RegExp(data.email, 'i')
Same as first comment

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/handler.js
> +          email: new RegExp(email, 'i')
Same as first comment

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/util.js
> +                username: new RegExp(username, 'i')
Look for both statements if they can be reduced by the same method as in handler.js

2017-06-06 11:23 UTC, rmeissn commented on application/controllers/util.js
> +              const sameEMail = curr.email.toLowerCase() === email.toLowerCase();
If in database always lowercase, remove the call here

2017-06-06 12:19 UTC, TBoonX commented on application/controllers/handler.js
> +    let identifier = decodeURI(req.params.identifier).replace(/\s/g,'');
As the identifier is an integer or a string I validate with the correct regex if integer validations fails

2017-06-08 12:04 UTC, rmeissn commented
I've tested the Service-API:
* Using /user/{id}/profile PUT to change user information, I am able to exchange case-sensitive chars of the username. E.g. change rmeissn to RmeiSsn
* I can't test /usergroup/createorupdate in Swagger as members is never issued as an array (maybe it's possible to fix it)

I haven't tested social login and usergroups, but code looks good.

2017-06-08 13:08 UTC, TBoonX commented
@rmeissn 
* We liked to keep the users preference thus I would say its okay to change the case sensitivity of the chars. It is not used in the frontend thus I would like to keep this logic.
* I fixed the swagger problem

Additionally I added case insensitivity to the route which returns the users public profile, as requested by kostis: https://slidewiki.atlassian.net/wiki/pages/viewpage.action?pageId=43251468

2017-06-08 13:53 UTC, rmeissn commented
About the Migration script: I think you can simplify it a lot.
What you want to do is: map users (email to lowercase and remove not allowed chars from usernames) and group users by username (to group users with the same usernames). Subsequently map all users to users and map groups of users to users (username is modified, e.g. added "_", emit() is called several times for a group).
Thus you would be able to get rid of the entire reduce functions (and thus LOC and logic).

2017-06-08 14:14 UTC, TBoonX commented
OK this could be done later. Thus @kadevgraaf please merge it.

2017-06-08 14:32 UTC, merged