Swik 1412 merge from template
slidewiki/user-service pull request #27
Opened 2017-07-03 07:31 UTC by TBoonX

I merged the new version of the template.
I had to fix alot of linter errors

2017-07-04 09:12 UTC, rmeissn requested changes
Looks okay so far. Please answer to the comments of the review and merge latest template again, as another PR has been merged into it.

2017-07-04 09:12 UTC, rmeissn commented on application/db_migration_usernames.js
> +            emit(this.username.toLowerCase().replace(/[|\s&;$%&§{[\]}@"<>()+,!?\-._~=*+#;\\/]/g, ''), this);
Please use the old regex and deactivate eslint for this line.

2017-07-04 09:12 UTC, rmeissn commented on application/db_migration_usernames.js
> +                  this.value.username = this.value.username.replace(/[|\s&;$%&§{[\]}@"<>()+,!?=*+#;\\/]/g,'_');
Please use the old regex and deactivate eslint for this line.

2017-07-04 09:12 UTC, rmeissn commented on application/db_migration_usernames.js
> +                      let username = user.username.replace(/[|\s&;$%&§{[\]}@"<>()+,!?=*+#;\\/]/g,'_');
Please use the old regex and deactivate eslint for this line.

2017-07-04 09:12 UTC, rmeissn commented on application/tests/unit_database_helper.js
> +// example unit tests
The entire file might have been added on coincidence. Please recheck

2017-07-04 13:16 UTC, TBoonX commented
@rmeissn please review again

2017-07-10 11:34 UTC, rmeissn commented
All questions have been answered/problems were resolved. As still all unit/integrations tests pass, I'm fine with merging it.

But we should still wait for the 2.4 release, before merging this into master, right? @bwulff

2017-07-10 11:34 UTC, rmeissn approved these changes

2017-09-21 09:12 UTC, rmeissn commented
Please resolve the conflicts and than merge these changes to master.

2017-09-25 11:58 UTC, merged